global.constants = {
    const_tools: '工具',
    const_main: '首页',
    const_home: '我的',
    const_url: 'http://122.51.161.53:3000',
    const_api_url: 'http://122.51.161.53:9093/api',
    const_tools_header_name: '工具',
    const_tools_footer_end_name: '结束',
    const_tools_panel_filesize_name: '大小',
    const_tools_panel_access_number_name: '次访问',
    const_tools_panel_access_name: '地址',
    const_home_statement_name: '软件许可及服务协议',
    const_home_qrcode_name: '主页二维码',
    const_home_register_tool_name: '注册工具',
    const_home_register_tool_title: '名称',
    const_home_register_tool_version: "版本号",
    const_home_register_tool_url: "URL",
    const_home_register_tool_des: "功能描述",
    const_home_register_tool_logo: "Logo",
    const_home_register_tool_tag_safe: "安全",
    const_home_register_tool_tag_video: "视频",
    const_home_register_tool_tag_data: "数据",
    const_home_register_tool_tag_audio: "音频",
    const_home_register_tool_tag_image: "图片",
    const_home_register_tool_submit: "提交",
};

